
const Action = [
    {
        id: 1,
        title: 'Code Geass',
        image: 'https://firebasestorage.googleapis.com/v0/b/animesanctuary-c56e6.appspot.com/o/action%2Fcode_geass.jpg?alt=media&token=9cb9f79b-fc01-414a-8352-8ec76f3b9bb8',
        genre: ['Action', 'Award Winning', 'Drama', 'Sci-Fi'],
        episodes: 25,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GY2P9ED0Y/code-geass',
        youtube: 'https://www.youtube.com/watch?v=v-AGjx0N24U',
        description: "Code Geass is an essential watch for anime aficionados. It chronicles the journey of a prince harnessing his intellect to defy his father's empire. The series introduces a unique power, the Geass, enabling the protagonist to issue a single command to anyone. With its blend of mecha battles, romance, and psychological intrigue, this anime stands as a timeless classic, earning our unwavering acclaim as one of the greatest of its era and beyond.",
        url: 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
    },

    {
        id: 2,
        title: 'Attack on Titan',
        image: 'https://firebasestorage.googleapis.com/v0/b/animesanctuary-c56e6.appspot.com/o/action%2Faot.jpg?alt=media&token=3e9bafaa-36ce-4026-9047-3aa3a84786d0',
        genre: ['Action', 'Award Winning', 'Drama', 'Suspense'],
        episodes: 25,
        seasons: 4,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan',
        youtube: 'https://www.youtube.com/watch?v=MGRm4IzK1SQ',
        description: "Don't judge Attack on Titan solely by its title or trailer; while it may appear to follow the conventional trope of a hero battling titans to save civilization, it's far from cliché. This anime delves deep into emotions, politics, and features unforgettable characters and experiences. Prepare yourself for an emotional rollercoaster filled with intense drama, numerous twists, and turns in every episode. Watch Attack on Titan if you crave a gripping and multifaceted narrative that defies expectations.",
        url: 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
    },

    {
        id: 3,
        title: "Darwin's game",
        image: 'https://firebasestorage.googleapis.com/v0/b/animesanctuary-c56e6.appspot.com/o/action%2Fdarwin.jpg?alt=media&token=e609158d-c3fe-4b90-8476-96e9c52f794c',
        genre: ['Action', 'Sci-Fi', 'Super Power', 'Survival'],
        episodes: 11,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G61X24PZ6/darwins-game',
        youtube: 'https://www.youtube.com/watch?v=_cLxzQoNVpo',
        description: "At first glance, the anime may seem like a cacophony of bizarre creatures wielding extraordinary powers, but beneath the surface lies a meticulously crafted storyline that defies convention. As the plot unfolds, viewers are drawn into a relentless whirlwind of suspense and intrigue, where every twist and turn keeps them on the edge of their seats. Darwin's Game seamlessly combines elements of high-stakes gaming with the primal instinct for survival, creating a mesmerizing experience for enthusiasts of battle royales and the survival of the fittest genre. With each confrontation, the tension mounts, pushing characters to their limits as they navigate a treacherous landscape fraught with danger.",
        url: 'https://myanimelist.net/anime/38656/Darwins_Game',
    },

    {
        id: 4,
        title: "Kabaneri of the iron fortress",
        image: 'https://firebasestorage.googleapis.com/v0/b/animesanctuary-c56e6.appspot.com/o/action%2Fkabaneri.jpg?alt=media&token=8cbd1f0e-df6d-41af-bd45-0f4e715b0f42',
        genre: ['Action', 'Mystery', 'Suspence'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GR24GX896/kabaneri-of-the-iron-fortress',
        youtube: 'https://www.youtube.com/watch?v=lQ9VjFBqfH8',
        description: "From searing loss to triumphant victory, every moment resonates deeply. Witness a journey of self-discovery and redemption, where friends and foes blur in war's chaos. Kabaneri of the Iron Fortress is a testament to humanity's resilience, where every victory is hard-won and every defeat carries weight. Prepare for a whirlwind of emotions in this unforgettable tale of courage, hope, and the unyielding spirit of humanity.",
        url: 'https://myanimelist.net/anime/28623/Koutetsujou_no_Kabaneri?q=kabaneri&cat=anime',
    },


    {
        id: 5,
        title: "Bananafish",
        image: 'https://firebasestorage.googleapis.com/v0/b/animesanctuary-c56e6.appspot.com/o/action%2Fbananafish.jpg?alt=media&token=c770c60d-652e-4d9f-85d9-9d8ad9c9fa8b',
        genre: ['Action', 'Adventure', 'Drama', 'Suspence'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.80b3e377-24f4-5ba0-f7ed-4da209b3aaee?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://www.youtube.com/watch?v=4IsT8wS3Qq8',
        description: "Bananafish is AMAZING. Each episode is a rollercoaster of emotions, pulling viewers into a gripping narrative where the line between friend and foe blurs. As characters grapple with the complexities of their identities, the stakes soar to new heights. But beneath the surface lies a web of intrigue and betrayal, challenging protagonists to confront their darkest fears. In this high-stakes game of cat and mouse, nothing is as it seems. From the outside, figure out who the villain is and deal with it, simple no? Well not exactly… You'll thank me later",
        url: 'https://myanimelist.net/anime/36649/Banana_Fish?q=banana&cat=anime',
    },

    {
        id: 6,
        title: "Tower of God",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ftower_of_god.jpg?alt=media&token=1fcd5dc7-1a0e-404c-b912-6bc07879f16a',
        genre: ['Action', 'Adventure', 'Drama', 'Fantasy'],
        episodes: 13,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G6J0G49DR/tower-of-god',
        youtube: 'https://www.youtube.com/watch?v=RNyClma6awo',
        description: "An exhilarating and captivating anime that will take you on an epic journey filled with breathtaking action, complex characters, and mind-bending twists. From the moment you step into the mysterious and dangerous Tower, you'll be gripped by its gripping storyline and entranced by its stunning animation.\n\n The main protagonist, Bam, will steal your heart with his unwavering determination and resilience as he navigates the treacherous trials and challenges of the Tower to reunite with his beloved Rachel.\n\n Along the way, he forges unbreakable bonds with unforgettable allies like the fierce and loyal Khun and the enigmatic Princess Yuri. As the secrets of the Tower slowly unravel and alliances are tested, you'll find yourself on the edge of your seat, eagerly anticipating each new revelation and eagerly rooting for Bam's success. Tower of God is a masterful blend of action, intrigue, and heart, sure to leave you breathless and craving for more.",
        url: 'https://myanimelist.net/anime/40221/Kami_no_Tou',
    },

    {
        id: 7,
        title: "Owari no Seraph",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fowari_no_seraph.jpg?alt=media&token=9987a831-8b69-49e0-8163-dd0a1f718f18',
        genre: ['Action', 'Drama', 'Fantasy'],
        episodes: 12,
        seasons: 2,
        type: 'TV',
        funanimation: 'https://www.funimation.com/shows/seraph-of-the-end-vampire-reign',
        youtube: 'https://www.youtube.com/watch?v=NtzDAmRhD9s',
        description: "Oh, my goodness, Owari no Seraph is an absolute rollercoaster of emotions and excitement! From the very first episode, I was drawn into this post-apocalyptic world where humans are enslaved by vampires, and the only hope for humanity lies in the hands of a group of young, determined fighters.\n\n The characters are so well-developed, each with their own struggles and motivations that tug at your heartstrings. Yuuichirou's fiery determination to avenge his fallen comrades and protect his newfound family is both inspiring and heart-wrenching.\n\n The action sequences are pulse-pounding and intense, keeping me on the edge of my seat throughout the entire series.But it's not just about the battles and bloodshed; there are also moments of friendship, loyalty, and sacrifice that will leave you in tears.\n\n The plot twists and turns had me gasping in shock and anticipation, and the stunning animation and soundtrack only added to the overall exhilarating experience. Overall, Owari no Seraph is a masterpiece that combines thrilling action, deep emotions, and a gripping storyline that will keep you hooked from start to finish. Trust me, you do not want to miss out on this anime!",
        url: 'https://myanimelist.net/anime/26243/Owari_no_Seraph',
    },

    {
        id: 8,
        title: "Fena: Pirate Princess",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2FKaizoku_Oujo.jpg?alt=media&token=f2459e59-4c70-4f61-87ce-0c12d35f987d',
        genre: ['Action', 'Adventure', 'Fantasy'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GZJH3DPM1/fena-pirate-princess',
        youtube: 'https://www.youtube.com/watch?v=ci_Vauuz7AQ',
        description: "Arr matey! Let me tell you about the swashbuckling adventure that is Fena: Pirate Princess!\n\n This anime is a treasure trove of excitement, with its gripping storyline, stunning animation, and unforgettable characters that will steal your heart faster than a pirate raid at sea! From the moment Fena sets sail on her quest to find her destiny, I was hooked!\n\n The thrilling action scenes had me on the edge of my seat, the emotional moments tugged at my heartstrings, and the strong bonds between Fena and her loyal crew left me feeling all warm and fuzzy inside. Each episode was a voyage of discovery, filled with mystery, danger, and moments of pure joy.\n\n The ending was a bittersweet symphony that left me craving for more adventures on the high seas. It is truly a gem of an anime that shines brighter than any treasure in the seven seas! Aye, me hearties, this show is truly amazing and deserves all the praise and accolades it receives!",
        url: 'https://myanimelist.net/anime/42544/Kaizoku_Oujo',
    },

    {
        id: 9,
        title: "Akudama Drive",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fakudama_drive.jpg?alt=media&token=8b0a96bf-5e6d-48b0-81cc-042c3fa9730c',
        genre: ['Action', 'Sci-Fi', 'Suspence'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GKEH2G440/akudama-drive',
        youtube: 'https://www.youtube.com/watch?v=47QY-u0CXMo',
        description: "An absolute thrill ride from start to finish, a high-octane blend of action, suspense, and futuristic chaos that will leave you on the edge of your seat craving for more. With its stunning visuals, dynamic characters, and mind-bending plot twists, this anime pushes the boundaries of creativity and keeps viewers utterly captivated.\n\n From the adrenaline-pumping fight scenes to the intricate world-building, every moment is a masterpiece that leaves a lasting impact. The intensity and raw emotion woven into every episode will make your heart race and your jaw drop in awe.\n\nAkudama Drive is a rollercoaster of emotions that will have you rooting for the anti-heroes, questioning your perspective on morality, and ultimately, leaving you in sheer amazement at its brilliance. It's a wild, exhilarating journey that you won't soon forget.",
        url: 'https://myanimelist.net/anime/41433/Akudama_Drive',
    },

    {
        id: 10,
        title: "Dororo",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdororo.jpg?alt=media&token=e127b6d5-19db-4d4c-869e-34423afc9836',
        genre: ['Action', 'Supernatural', 'Adventure'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/Dororo/dp/B07MBRLTPK',
        youtube: 'https://www.youtube.com/watch?v=YgHPBwLu0BA',
        description: "The story follows the journey of Hyakkimaru, a young swordsman on a quest to reclaim his stolen body parts from demons, with the help of Dororo, a plucky young thief. The dynamic between the two protagonists is heartwarming and their character development throughout the series is beautifully crafted. The animation is breathtaking, with fluid fight scenes and detailed landscapes that truly immerse you in the world of samurais and supernatural beings.\n\nEach episode is filled with intense emotions, from heart-wrenching tragedies to heartwarming triumphs, keeping you on the edge of your seat until the very end. But what truly sets Dororo apart is its exploration of themes such as redemption, sacrifice, and the true meaning of humanity. It forces you to question your morals and beliefs, leaving a lasting impact long after the final episode. Dororo is not just an anime, it's a rollercoaster of emotions that will stay with you forever.",
        url: 'https://myanimelist.net/anime/37520/Dororo',
    },

    {
        id: 11,
        title: "Vinland Saga",
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fvinland_saga.jpg?alt=media&token=b299a5fb-3eb9-48c4-a75c-457ec8487168',
        genre: ['Action', 'Adventure', 'Drama'],
        episodes: 24,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GEXH3WKK0/vinland-saga',
        youtube: 'https://www.youtube.com/watch?v=f8JrZ7Q_p-8',
        description: "I know I mentioned 10 anime above but I abviously couldn't skip on this masterpiece...\n\nVinland Saga is an epic tale of revenge, redemption, and the pursuit of true freedom that will tug at your heartstrings and leave you breathless. From the moment the stunning animation begins, you are transported into a world filled with intense battles, intricate political intrigue, and deep emotional connections.\n\nThe characters are complex and multifaceted, each with their own struggles and motivations that will resonate with you on a profound level. But beyond the exhilarating fight scenes and gripping plot twists, Vinland Saga is ultimately a story about the resilience of the human spirit and the power of forgiveness. It will make you laugh, cry, and cheer for the characters as they navigate the unforgiving world of medieval Scandinavia.",
        url: 'https://myanimelist.net/anime/37521/Vinland_Saga',
    },


]

export default Action;
