

const Classics = [

    {
        id: 1,
        title: 'Naruto / Naruto Shippuden',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fnaruto.jpg?alt=media&token=52f550aa-c63e-4381-bb53-714dbeeb18d8',
        genre: ['Adventure', 'Action', 'Fantasy'],
        episodes: 220,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GY9PJ5KWR/naruto',
        youtube: 'https://www.youtube.com/watch?v=QczGoCmX-pI',
        description: "Naruto is not just an anime, it's an exhilarating journey of self-discovery, friendship, and determination that grips your heart and soul from the very first episode. The complex characters, intense battles, and touching moments fill you with a rollercoaster of emotions - from excitement to sadness to pure joy. Witnessing Naruto's growth from a lonely, misunderstood outcast to a brave and powerful ninja is nothing short of inspiring. Each arc is carefully crafted, leaving you on the edge of your seat craving for more. The bonds formed between Naruto and his friends are so beautifully portrayed, it's impossible not to be moved. This anime is a masterpiece that will forever hold a special place in my heart, a timeless classic that continues to enchant and captivate viewers worldwide. Believe it!",
        url: 'https://myanimelist.net/anime/20/Naruto',
    },

    {
        id: 2,
        title: 'One Piece',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fone_piece.webp?alt=media&token=18a20ab0-22d7-4bec-b97b-f1cc45fda551',
        genre: ['Adventure', 'Action', 'Fantasy'],
        episodes: "1000+",
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece',
        youtube: 'https://www.youtube.com/watch?v=aJKPk1MriFo',
        description: 'As I dive into the vast and wondrous world of One Piece, my heart swells with joy and excitement. The journey of Monkey D. Luffy and his crew is a rollercoaster of emotions, laughter, and tears. Every episode is filled with jaw-dropping battles, heartwarming friendships, and unforgettable adventures that leave me on the edge of my seat, craving for more. The intricate storytelling, diverse characters, and meaningful themes of friendship and dreams make One Piece a masterpiece that captivates my soul.',
        url: 'https://myanimelist.net/anime/21/One_Piece?q=one%20piece&cat=anime',
    },

    {
        id: 3,
        title: 'Dragon Ball Z',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdragon_ball.webp?alt=media&token=654b747e-bf86-4ff6-af51-633843560cd2',
        genre: ['Adventure', 'Action', 'Fantasy'],
        episodes: 291,
        seasons: 3,
        type: 'TV',
        amazonPrime: 'https://www.amazon.com/Dragon-Ball-Z-Season-1/dp/B012S1Q9YO',
        youtube: '',
        description: 'Dragon Ball Z, with its iconic battles and powerful transformations, ignited a fire within me that will never die. The epic clashes between Goku and his enemies, the bonds of brotherhood among the Z fighters, and the endless pursuit of strength and justice resonate with me on a profound level. Watching Goku push his limits and protect the Earth fills me with a sense of courage and determination that transcends mere entertainment.',
        url: 'https://myanimelist.net/anime/813/Dragon_Ball_Z?q=dragon%20ball%20z&cat=anime',
    },

    {
        id: 4,
        title: 'Yu Yu Hakusho',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fyuyu.jpg?alt=media&token=4bf29e31-42ee-4d7a-aa6a-a69af5b0e51e',
        genre: ['Action', 'Fantasy'],
        episodes: 112,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GR9PKENW6/yu-yu-hakusho',
        youtube: 'https://www.youtube.com/watch?v=bGc1Na8mlw0',
        description: 'Yu Yu Hakusho delves deep into the supernatural world, blending intense battles with heartfelt moments of camaraderie and self-discovery. The journey of Yusuke Urameshi from delinquent to spirit detective is a captivating ride that immerses me in a world of demons, psychics, and ancient prophecies. The themes of redemption, loyalty, and sacrifice are beautifully woven into the narrative, leaving a lasting impact on my heart and mind.',
        url: 'https://myanimelist.net/anime/392/Yuu%E2%98%86Yuu%E2%98%86Hakusho',
        gem: 'gem',
    },

    {
        id: 5,
        title: 'ZatchBell',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fzatchbell.jpg?alt=media&token=a5398165-1bcb-4cbc-b950-ade794154359',
        genre: ['Action', 'Fantasy', 'Adventure'],
        episodes: 150,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.com/Zatch-Bell-Season-1/dp/B00H2EPKNE',
        youtube: 'https://www.youtube.com/watch?v=RtpQ_05RsjY',
        description: 'The bond between Zatch and Kiyo, the thrilling mamodo battles, and the emotional depth of the characters create a captivating tale that tugs at my heartstrings. The message of believing in oneself and the power of friendship shines brightly throughout the series, making it a timeless treasure that I hold dear to my heart.',
        url: 'https://myanimelist.net/anime/250/Konjiki_no_Gash_Bell?q=zatchbe&cat=anime',
    },

    {
        id: 6,
        title: 'Katekyo Hitman Reborn',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Freborn.jpg?alt=media&token=655a8ab2-082d-4f1c-8ca9-dca35936ae70',
        genre: ['Action', 'Fantasy', 'Adventure'],
        episodes: 150,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRNQ13VQR/reborn',
        youtube: 'https://www.youtube.com/watch?v=iL4m2-nhOuI',
        description: "Katekyo Hitman Reborn! isn't just an anime—it's a passionate odyssey that resonates with the deepest recesses of my heart, leaving an indelible mark that will endure for eternity. The characters, from the lovably clumsy Tsuna to the enigmatic Hitman Reborn, etch themselves into my soul, becoming cherished companions on this extraordinary journey. The battles are not merely clashes of strength but visceral expressions of the characters' growth and determination. With every victory and defeat, I am swept away by a whirlwind of emotions, from heart-pounding excitement to tearful triumph.",
        url: 'https://myanimelist.net/anime/1604/Katekyou_Hitman_Reborn?q=katekyo&cat=anime',
    },

    {
        id: 7,
        title: 'City Hunter',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fcity_hunter.jpg?alt=media&token=d869a4cf-7be3-4d30-8b9b-600e4cd3fe13',
        genre: ['Action', 'Comdedy', 'Mystery'],
        episodes: 51,
        seasons: 4,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G6P5M4156/city-hunter',
        youtube: 'https://www.youtube.com/watch?v=lYlIeUpY6WQ',
        description: "With its captivating storytelling and unforgettable characters, City Hunter isn't just an anime—it's a passionate journey that ignites the soul and leaves an indelible mark on the heart. It's not just good; it's a symphony of emotions that resonates with every fiber of my being.",
        url: 'https://myanimelist.net/anime/1470/City_Hunter?q=city%20hunt&cat=anime',
    },

    {
        id: 8,
        title: 'Claymore',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fclaymore.jpg?alt=media&token=d3497d8e-07d4-4ea2-9690-b6acafbb64ba',
        genre: ['Action', 'Adventure', 'Fantasy'],
        episodes: 26,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRMEKVG8Y/claymore',
        youtube: 'https://www.youtube.com/watch?v=c5DDD0ofspk',
        description: 'A dark and gritty anime that delved deep into complex themes of morality, sacrifice, and redemption. The fierce female warriors known as Claymores battling against terrifying monsters known as Yoma had me captivated from start to finish.',
        url: 'https://myanimelist.net/anime/1818/Claymore?q=claymore&cat=anime',
    },

    {
        id: 9,
        title: 'Detective Conan / Case Closed',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdetective_conan.jpg?alt=media&token=0ba4f6a1-bf29-4c00-a79c-3f1a801fa0b9',
        genre: ['Adventure', 'Mystery'],
        episodes: "1100+",
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G6JQVM3ER/case-closed-detective-conan',
        youtube: 'https://www.youtube.com/watch?v=1Mz9orl7bDw',
        description: 'Detective Conan is a timeless classic that combines mystery, suspense, and a touch of comedy in a way that keeps viewers coming back for more. The clever deductions of the brilliant young detective Conan Edogawa never fail to impress me, and the intricate cases he solves always leave me in awe.',
        url: 'https://myanimelist.net/anime/235/Meitantei_Conan',
    },

    {
        id: 10,
        title: 'Cowboy Bebop',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fcowboy_bebop.jpg?alt=media&token=ad59ac65-6e0c-435a-baf0-dc6a5e1ea523',
        genre: ['Adventure', 'Action', 'Sci-Fi'],
        episodes: 26,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GYVNXMVP6/cowboy-bebop',
        youtube: 'https://www.youtube.com/watch?v=AJKEXDKBVdk',
        description: 'A masterpiece that seamlessly blends elements of western, noir, and sci-fi genres into a mesmerizing and unforgettable anime experience. The bounty hunting adventures of the eclectic crew aboard the Bebop ship, set against a backdrop of jazz music and stunning animation, had me completely enthralled. Each episode was a masterpiece in storytelling and character development that left me yearning for more.',
        url: 'https://myanimelist.net/anime/1/Cowboy_Bebop?q=cowboy&cat=anime',
    },

]

export default Classics