
const Mystery = [
    {
        id: 1,
        title: 'Anime1',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 2,
        title: 'Anime2',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 3,
        title: 'Anime3',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 4,
        title: 'Anime4',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 5,
        title: 'Anime5',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 6,
        title: 'Anime6',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 7,
        title: 'Anime7',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 8,
        title: 'Anime8',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 9,
        title: 'Anime9',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

    {
        id: 10,
        title: 'Anime10',
        image: '',
        genre: ['', '', '', ''],
        episodes: 20,
        rating: 8.5,
        type: 'TV',
        gif: '',
        cruncyroll: '',
        youtube: '',
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint, officia sapiente? Voluptas possimus impedit error molestiae, libero architecto inventore temporibus necessitatibus consequatur fugit iure cupiditate illum sit sint praesentium quas.",
        url: '',
    },

]

export default Mystery