
const Mystery = [
    {
        id: 1,
        title: 'Babylon',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fbabylon.jpg?alt=media&token=e36c406a-35d6-4033-bcd5-960351cda284',
        genre: ['Mystery', 'Suspense'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.16b7ed42-4879-79bf-3614-6110dad9e409?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://www.youtube.com/watch?v=lmwuU8MTa9Q&ab_channel=phantomsword',
        description: 'Babylon is a mind-bending rollercoaster of an anime that will leave you on the edge of your seat from start to finish. It seamlessly weaves together elements of mystery, thriller, and political drama to deliver a truly gripping storyline. The characters are complex and multi-dimensional, keeping you guessing their true motives until the very end. The series delves into dark and thought-provoking themes, challenging viewers to question the nature of justice and morality. With its clever plot twists and suspenseful atmosphere, Babylon keeps you hooked, eagerly anticipating each new revelation. Prepare to be immersed in a world where nothing is as it seems, and trust no one. This anime is a must-watch for anyone craving a truly captivating and enigmatic experience."',
        url: 'https://myanimelist.net/anime/37525/Babylon',
    },

    {
        id: 2,
        title: 'Darker than Black',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdarker_than_black.jpg?alt=media&token=ca8e6d87-7524-4e9b-9a8a-daa24d6e3f4b',
        genre: ['Action', 'Mystery', 'Sci-Fi'],
        episodes: 25,
        seasons: 2,
        type: 'TV',
        amazonPrime: 'https://www.amazon.com/Darker-Than-Black/dp/B0718SWDVK',
        youtube: 'https://www.youtube.com/watch?v=upx-_9-RjoE&ab_channel=MokiNS',
        description: 'Darker than Black is an electrifying anime that captivates from the first episode to the last with its thrilling action sequences and complex characters. The show follows mysterious entities known as Contractors who possess supernatural powers but at a steep cost. The intricate plot keeps you on the edge of your seat as secrets are slowly unraveled, creating an atmosphere of suspense and intrigue. The protagonist, Hei, is a brooding and enigmatic figure with a dark past, adding depth to the narrative. The animation is stunning, perfectly complementing the dark and gritty tone of the series. Darker than Black is a must-watch for any anime fan craving a blend of supernatural abilities, intense battles, and a touch of mystery that will leave you wanting more.',
        url: 'https://myanimelist.net/anime/2025/Darker_than_Black__Kuro_no_Keiyakusha',
    },

    {
        id: 3,
        title: 'Erased',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ferased.png?alt=media&token=1146c8fe-496b-4b6b-86e7-c11a868845ad',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GYGG92K7Y/erased',
        youtube: 'https://www.youtube.com/watch?v=g8tTxuO1oIY&ab_channel=AniplexUSA',
        description: 'Breathtaking gem of an anime that will grip you from the very first episode and never let go. The story follows Satoru, a man with the mysterious ability to go back in time and prevent tragedies from happening. As he races against the clock to save his friends and solve a series of murders, the tension is palpable, keeping you on the edge of your seat with every twist and turn. The emotional depth of the characters, combined with the suspenseful plot, creates a truly immersive experience that will leave you constantly guessing. With its stunning animation and haunting soundtrack. Dive into this enigmatic world, and let yourself be swept away by its brilliance. This anime is a masterpiece',
        url: 'https://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi',
        gem: 'gem',
    },

    {
        id: 4,
        title: 'Moriarty the Patriot',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fmoriarty.jpg?alt=media&token=add04c8e-33f8-4ef6-b2c6-852c2c72e5d9',
        genre: ['Mystery', 'Suspense'],
        episodes: 11,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GXJHM379D/moriarty-the-patriot',
        youtube: 'https://www.youtube.com/watch?v=zDX2dfLqhjo&ab_channel=CrunchyrollDubs',
        description: 'Moriarty is a great that will take you on a thrilling ride full of deception, intrigue, and brilliant strategic planning. The stunning animation brings to life the dark and atmospheric setting of Victorian London, setting the stage for a captivating story of revenge and justice. Every episode keeps you on the edge of your seat, unraveling the enigmatic plans of the cunning protagonist, William James Moriarty. The way he orchestrates his schemes with precision and intellect is nothing short of genius. The complex characters, gripping plot twists, and moral dilemmas will make you question your own sense of right and wrong. Moriarty the Patriot is a must-watch for anyone craving a dark, mysterious, and emotionally charged anime experience like no other.',
        url: 'https://myanimelist.net/anime/40911/Yuukoku_no_Moriarty',
    },

    {
        id: 5,
        title: 'Promised Neverland',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fpromised_neverland.jpg?alt=media&token=392303bd-5df0-4cb9-8a9b-fd1d0b03361d',
        genre: ['Mystery', 'Sci-Fi', 'Suspense'],
        episodes: 12,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GYVD2K1WY/the-promised-neverland',
        youtube: 'https://www.youtube.com/watch?v=dJhzDlwvwrI&ab_channel=BiordiFilms',
        description: 'Unforgettable experience. The story follows a group of orphaned children who uncover a dark secret about their idyllic home and must use their wits to navigate a twisted web of deceit and danger. As the plot unfolds, the tension skyrockets, leaving you gasping at each shocking revelation. The intricate character development, heart-pounding suspense, and jaw-dropping twists make The Promised Neverland a must-watch for any anime fan. Trust me, this anime will keep you guessing and second-guessing until the very end, leaving you craving for more!',
        url: 'https://myanimelist.net/anime/37779/Yakusoku_no_Neverland',
    },

    {
        id: 6,
        title: 'Terrror in Resonance',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fterror_in_resonance.jpg?alt=media&token=b5926151-454e-427c-8e9e-fcd11ec11ccc',
        genre: ['Mystery', 'Suspense'],
        episodes: 11,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G675W00MR/terror-in-resonance',
        youtube: 'https://www.youtube.com/watch?v=nLVy50LnLMM',
        description: 'This thrilling anime follows the enigmatic duo Nine and Twelve as they carry out a series of elaborate terrorist acts, all while leaving cryptic clues behind for the authorities to decipher. The tension is palpable, with twists and turns that will leave you on the edge of your seat, desperate to uncover the truth behind their motives. The deep and complex characters, stunning animation, and haunting soundtrack create a truly immersive experience that will stay with you long after the final credits roll. Terror in Resonance is a thought-provoking rollercoaster of emotions that will make you question morality, justice, and the power of human connection.',
        url: 'https://myanimelist.net/anime/23283/Zankyou_no_Terror',
    },
    {
        id: 7,
        title: 'Death Note',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdeath_note.jpg?alt=media&token=6162040f-b752-4a51-8c0a-1d19e481fe2a',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 37,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.70af037c-8d1b-87dd-5ac0-d60cb76d89b4?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://www.youtube.com/watch?v=NlJZ-YgAt-c',
        description: "Death Note is an electrifying masterpiece that will have your heart racing with every twist and turn! The story follows the genius high school student, Light Yagami, who obtains a death god's notebook that allows him to kill anyone just by knowing their name. The cat-and-mouse game between Light and the enigmatic detective, L, will leave you on the edge of your seat, questioning your own morals as you witness their battle of wits unfold. The complex characters, mind-bending plot, and moral dilemmas explored in Death Note will keep you guessing until the very last moment. It's a thrilling rollercoaster of emotions, suspense, and intrigue that will leave you craving for more. ",
        url: 'https://myanimelist.net/anime/1535/Death_Note',
    },
    {
        id: 8,
        title: 'Steins Gate',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fsteins_gate.jpg?alt=media&token=2d1f63b9-4663-4d52-b601-e7898251a6cc',
        genre: ['Drama', 'Sci-Fi', 'Mystery'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        hulu: 'https://www.hulu.com/series/steinsgate-1e6bb91f-1b9f-471e-8bd3-ec7cb0de1869',
        youtube: 'https://www.youtube.com/watch?v=uMYhjVwp0Fk',
        description: "This anime is out of this world, it is an absolute masterpiece that will take you on a mind-bending, heart-pounding journey through the realms of time travel and parallel universes. The intricate plot will keep you on the edge of your seat, as you unravel the mysteries alongside the brilliant, yet eccentric characters. Every twist and turn will leave you gasping in awe and desperate for more. The emotional depth of the story will have you laughing, crying, and questioning your own reality. The attention to detail in the storytelling is impeccable, keeping you guessing until the very end. This is is not just an anime; it's an experience that will stay with you long after the credits roll.",
        url: 'https://myanimelist.net/anime/9253/Steins_Gate',
    },
    {
        id: 9,
        title: 'Made in Abyss',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fmade_in_abyss.jpg?alt=media&token=6553c6ec-c433-45a1-bb8e-582fbe8196f3',
        genre: ['Adventure', 'Fantasy', 'Mystery', 'Sci-Fi'],
        episodes: 13,
        type: 'TV',
        seasons: "2/3",
        amazonPrime: 'https://www.amazon.com/MADE-IN-ABYSS-Season-1/dp/B073S1Y7BZ',
        youtube: 'https://www.youtube.com/watch?v=kqBNQEUI8dM',
        description: "From its stunning animation to its brilliant world-building, this anime is a true work of art. The sense of mystery and wonder that permeates every episode will leave you on the edge of your seat, eager to uncover the secrets hidden within the Abyss. The characters are richly developed, the story is compelling, and the emotional impact is palpable. It's a rollercoaster of emotions that will have you hooked from start to finish.",
        url: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
    },
    {
        id: 10,
        title: 'Summertime Render',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fsummertime_render.png?alt=media&token=bc7ebedf-a414-4e31-8289-4b24b38f340b',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 25,
        seasons: 1,
        type: 'TV',
        hulu: 'https://www.hulu.com/series/summer-time-rendering-5e235d03-75bc-4322-9c10-c2e49a1ca26d',
        youtube: 'https://www.youtube.com/watch?v=Js9ZHbAH3bE',
        description: "The story follows high school student Takuya and his friends as they uncover dark secrets and supernatural phenomena in their seemingly ordinary town. The plot is intricately woven with layers of intrigue and intricacy, leaving viewers constantly guessing and second-guessing every turn of events. The animation is stunning, the soundtrack is hauntingly beautiful, and the character development is top-notch. Trust me, once you start watching Summer Time Render, you won't be able to stop. It's a rollercoaster of emotions that will leave you craving for more. This anime is a must-watch for any mystery lover!",
        url: 'https://myanimelist.net/anime/47194/Summertime_Render',
    },

]

export default Mystery