
const SliceOfLife = [

    {
        id: 1,
        title: 'No Game no Life',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fno_game.jpg?alt=media&token=538c0dd9-662b-4b07-a32e-23c95e2c3279',
        genre: ['Slice of life', 'Comedy', 'Fantasy'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        hulu: 'https://www.hulu.com/series/no-game-no-life-6e4dd558-5c67-465f-be02-abc5226900bb',
        youtube: '',
        description: "",
        url: 'https://myanimelist.net/anime/19815/No_Game_No_Life?q=no%20game%20no%20life&cat=anime',
    },

    {
        id: 2,
        title: 'Kiznaiver',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fkiznaiver.png?alt=media&token=00dec6b8-e438-4eca-9a59-698d6baa2546',
        genre: ['Slice of life', 'Drama', 'Romance'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.aeb9fefb-f173-59c5-4802-b8ccc62599b5?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://youtu.be/cFZckSHAddI?si=_Eu08Ev1H7BoGfw2',
        description: "",
        url: 'https://myanimelist.net/anime/31798/Kiznaiver?q=kiznai&cat=anime',
    },

    {
        id: 3,
        title: 'Tsuki Ga Kirei',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ftsuki_ga_kirei.png?alt=media&token=8d5ffe12-3941-4b3c-826d-cda761c8dd7b',
        genre: ['Slice of life', 'Romance'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G6X0QPK8Y/tsukigakirei',
        youtube: 'https://www.youtube.com/watch?v=-3_hwxNg4b8',
        description: "",
        url: 'https://myanimelist.net/anime/34822/Tsuki_ga_Kirei?q=tsuki%20ga%20kire&cat=anime',
    },

    {
        id: 4,
        title: 'Classroom of the Elite',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fclassroom_of_the_elite.png?alt=media&token=646f1ae0-a710-43ee-98af-96d626d855e7',
        genre: ['Slice of life', 'Drama'],
        episodes: 12,
        seasons: 3,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRVN8MNQY/classroom-of-the-elite',
        youtube: 'https://www.youtube.com/watch?v=F_-y2LkkUjg',
        description: "",
        url: 'https://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e?q=classroom&cat=anime',
    },

    {
        id: 5,
        title: 'Ano Hana',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fano_hana.jpg?alt=media&token=c5ab3ba5-769b-42db-bf06-ded3a411cedb',
        genre: ['Slice of life', 'Drama'],
        episodes: 11,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GR19X2G26/anohana-the-flower-we-saw-that-day',
        youtube: 'https://youtu.be/x8fvwC5xVGg?si=TVZGbefpoOMJ3iS0',
        description: "",
        url: 'https://myanimelist.net/anime/9989/Ano_Hi_Mita_Hana_no_Namae_wo_Bokutachi_wa_Mada_Shiranai?q=ano%20hana&cat=anime',
    },

    {
        id: 6,
        title: 'Welcome to the NHK',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2FNHK.jpg?alt=media&token=090cc120-e3e2-4a3d-887e-6adf49ab21e7',
        genre: ['Slice of life', 'Comedy', 'Drama'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G6MGNDGW6/welcome-to-the-n-h-k',
        youtube: 'https://youtu.be/QYLsjJ8RThQ?si=5NqKpZNhBwlXEnz6',
        description: "",
        url: 'https://myanimelist.net/anime/1210/NHK_ni_Youkoso?q=welcome%20to%20the%20&cat=anime',
    },

    {
        id: 7,
        title: 'Wotakoi',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fwotakoi.jpg?alt=media&token=9ed22380-51e6-4800-ad90-93aadde8c294',
        genre: ['Slice of life', 'Comedy', 'Romance'],
        episodes: 11,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.f4b20f8f-3896-ab0c-4390-98052fe89b34?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://youtu.be/Uy90rTP9mLs?si=WkIEHwkinBYyBe7R',
        description: "",
        url: 'https://myanimelist.net/anime/35968/Wotaku_ni_Koi_wa_Muzukashii?q=wotaku&cat=anime',
    },

    {
        id: 8,
        title: 'GTO',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2FGTO.jpg?alt=media&token=cf24949a-cbbf-4fa7-853f-01a8e0d55888',
        genre: ['Slice of life', 'Comedy'],
        episodes: 43,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRQ4QG4GY/gto---the-animation',
        youtube: 'https://www.youtube.com/watch?v=HS2n3-e_0PE',
        description: "",
        url: 'https://myanimelist.net/anime/245/Great_Teacher_Onizuka?q=GTO&cat=anime',
    },

    {
        id: 9,
        title: 'Charlotte',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fcharlotte.jpeg?alt=media&token=38da7c85-aa84-4479-a190-7b79aa83b2e1',
        genre: ['Slice of life', 'Drama'],
        episodes: 13,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GYGG99WDY/charlotte',
        youtube: 'https://youtu.be/6AgEzww-a0w?si=ulFzUAIEXNjPQTmv',
        description: "",
        url: 'https://myanimelist.net/anime/28999/Charlotte?q=charlotte&cat=anime',
    },

    {
        id: 10,
        title: 'Spy X Family',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fspy_x_family.jpg?alt=media&token=55a1ff22-a852-4151-a585-259f3867fa86',
        genre: ['Slice of life', 'Comedy'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G4PH0WXVJ/spy-x-family',
        youtube: 'https://youtu.be/ofXigq9aIpo?si=R6lvGLW6nQ_8a3AJ',
        description: "",
        url: 'https://myanimelist.net/anime/50265/Spy_x_Family?q=spy%20x%20fami&cat=anime',
    },
    
]

export default SliceOfLife;