
const Underrated = [
    {
        id: 1,
        title: 'Mirai Niki',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fmirai_nikki.jpg?alt=media&token=79dcfb78-54d7-4a27-9d7d-5385104071e6',
        genre: ['Action', 'Supernatural'],
        episodes: 26,
        seasons: 1,
        type: 'TV',
        hulu: 'https://www.hulu.com/series/the-future-diary-0c43ee4a-8e87-4864-8496-7b215c2a3976',
        youtube: 'https://youtu.be/KfznTm8mJA4?si=5GEH2x06BlS2LNQC',
        description: "",
        url: 'https://myanimelist.net/anime/10620/Mirai_Nikki_TV?q=mirai%20nikki&cat=anime',
    },

    {
        id: 2,
        title: 'The Eminence in Shadow',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Femminence_in_shadow.jpg?alt=media&token=f1e4f5fa-cc1d-45eb-93d1-b26ad7875cd9',
        genre: ['Action', 'Comedy', 'Fantasy'],
        episodes: 20,
        seasons: 2,
        type: 'TV',
        amazonPrime: 'https://www.amazon.com/Eminence-Shadow-Season-Part/dp/B0B6QNPB3L',
        youtube: 'https://www.youtube.com/watch?v=Ciy0kf5EE3E',
        description: "",
        url: 'https://myanimelist.net/anime/48316/Kage_no_Jitsuryokusha_ni_Naritakute',
    },

    {
        id: 3,
        title: 'Beyond the Boundary',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fbeyond_the_boundary.jpg?alt=media&token=71e10eb2-ddf4-4620-a4d1-763ea4a567f1',
        genre: ['Action', 'Fantasy'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        hidive: 'https://www.hidive.com/tv/beyond-the-boundary',
        youtube: 'https://youtu.be/HU5EeNd1iXM?si=P1Qg0giV5oxbFyTl',
        description: "",
        url: 'https://myanimelist.net/anime/18153/Kyoukai_no_Kanata?q=beyond%20the%20&cat=anime',
    },

    {
        id: 4,
        title: 'Chainsaw man',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fchainsaw_man.jpg?alt=media&token=85c27fbd-cb28-4102-81e9-8229ff6f8c2b',
        genre: ['Action', 'Fantasy'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GVDHX8QNW/chainsaw-man',
        youtube: 'https://youtu.be/l96zmDlWCBk?si=e5gdh6cGCYYo7juM',
        description: "",
        url: 'https://myanimelist.net/anime/44511/Chainsaw_Man?q=chainsaw%20man&cat=anime',
    },

    {
        id: 5,
        title: 'Talentless Nana',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ftalentless_nana.png?alt=media&token=20630be8-5215-4f39-ae6b-b39ac80fa1c4',
        genre: ['Supernatural', 'Suspence'],
        episodes: 13,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GJ0H7Q87Z/talentless-nana',
        youtube: 'https://youtu.be/8MWnUBPslcs?si=sz6WLSqXASmRutFq',
        description: "",
        url: 'https://myanimelist.net/anime/41619/Munou_na_Nana?q=talentless&cat=anime',
    },

    {
        id: 6,
        title: 'Spice and Wolf',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fspice_and_wolf.jpg?alt=media&token=f1ced0c7-84f5-4534-9786-ef124dc0da48',
        genre: ['Adventure', 'Romance'],
        episodes: 13,
        seasons: 2,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/B0CHL4D1B2/ref=atv_dp_season_select_s1',
        youtube: 'https://youtu.be/gMPPrw_hVfM?si=AProYK1Kzt-HqwR9',
        description: "",
        url: 'https://myanimelist.net/anime/2966/Ookami_to_Koushinryou?q=spice%20and%20wolf&cat=anime',
    },

    {
        id: 7,
        title: 'Tomodachi Game',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ftomodachi.jpg?alt=media&token=9f34dae5-7c38-4ee4-aca8-702753588965',
        genre: ['Suspence'],
        episodes: 12,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GJ0H7QX0Z/tomodachi-game',
        youtube: 'https://youtu.be/y-hPQ0-orMM?si=DzrymiieswsOy9zN',
        description: "",
        url: 'https://myanimelist.net/anime/50273/Tomodachi_Game?q=Tomodachi&cat=anime',
    },

    {
        id: 8,
        title: 'Akame ga Kill!',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fakame_ga_kill.jpg?alt=media&token=e4a1c09a-6be2-4f47-b04e-b78cb41579e9',
        genre: ['Action', 'Adventure', 'Fantasy'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        hulu: 'https://www.hulu.com/series/akame-ga-kill-b6141bb5-8cd4-47dd-941c-711898814242',
        youtube: 'https://youtu.be/sCGWxQuSoDU?si=O05C50mTLpilvrQ_',
        description: "",
        url: 'https://myanimelist.net/anime/22199/Akame_ga_Kill?q=akame%20ga%20&cat=anime',
        gem: 'gem',
    },

    {
        id: 9,
        title: 'Kakegurui',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fkakegurui.jpg?alt=media&token=bce6d4fc-b93f-406a-8c4e-00ae15539881',
        genre: ['Drama', 'Mystery', 'Suspence'],
        episodes: 12,
        seasons: 2,
        type: 'TV',
        netflix: 'https://www.netflix.com/gb/title/80175351',
        youtube: 'https://youtu.be/cTlHQiRNVl0?si=4ilRxPlM5oxMe7By',
        description: "",
        url: 'https://myanimelist.net/anime/34933/Kakegurui?q=kakegu&cat=anime',
    },


    {
        id: 10,
        title: 'Guilty Crown',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fguilty_crown.jpg?alt=media&token=2b8c97b1-1be4-4076-bac4-f787238202d9',
        genre: ['Action', 'Drama', 'Sci-FI'],
        episodes: 22,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GZJH3D0N5/guilty-crown',
        youtube: 'https://youtu.be/JToS6gmWzgw?si=GolSxqrlSw0XAU4M',
        description: "",
        url: 'https://myanimelist.net/anime/10793/Guilty_Crown?q=guilty%20crown&cat=anime',
    },

    {
        id: 11,
        title: 'Twin Star Exorcists',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Ftwin_star_exorcists.png?alt=media&token=d983eb18-47a4-46d9-a9f0-839706a76eeb',
        genre: ['Action', 'Fantasy', 'Romance'],
        episodes: 50,
        seasons: 1,
        type: 'TV',
        amazonPrime: 'https://www.amazon.co.uk/gp/video/detail/amzn1.dv.gti.34b0b857-72f0-47af-900d-b57200b2ed00?autoplay=0&ref_=atv_cf_strg_wb',
        youtube: 'https://youtu.be/x5MGW5-iRY4?si=kdFI1Q37GbMU9UxZ',
        description: "",
        url: 'https://myanimelist.net/anime/32105/Sousei_no_Onmyouji?q=twin%20star&cat=anime',
    },

    {
        id: 12,
        title: 'Mushoku Tensei',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fmoshoku_tensei.jpg?alt=media&token=efb435ce-56a3-403a-a8d9-9c79247fbc15',
        genre: ['Adventure', 'Drama', 'Fantasy'],
        episodes: 11,
        seasons: 3,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G24H1N3MP/mushoku-tensei-jobless-reincarnation',
        youtube: 'https://youtu.be/k5VxfJpzy1Q?si=Kf79V932NcCeSUNo',
        description: "",
        url: 'https://myanimelist.net/anime/39535/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu?q=mushok&cat=anime',
    },

    {
        id: 13,
        title: 'Gleipnir',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fgleipnir.jpg?alt=media&token=46c9ed88-8797-41ac-a9b5-e1f0cac41fd8',
        genre: ['Action', 'Mystery', 'Supernatural'],
        episodes: 13,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/G9VHN9P7W/gleipnir',
        youtube: 'https://youtu.be/QzQ1sDFUJiA?si=jWn6gUg61x_eM4xH',
        description: "",
        url: 'https://myanimelist.net/anime/39463/Gleipnir?q=gleip&cat=anime',
    },

    {
        id: 14,
        title: 'Kono oto tomare',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fkono_oto_tomare.jpg?alt=media&token=389b4845-bc2b-418f-8ef3-5d15efc291c2',
        genre: ['Drama', 'Music'],
        episodes: 13,
        seasons: 2,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GRJ05PZ0Y/kono-oto-tomare-sounds-of-life',
        youtube: 'https://youtu.be/4-pKulFDkpM?si=5oydxHGZT-DQoPHN',
        description: "",
        url: 'https://myanimelist.net/anime/38080/Kono_Oto_Tomare',
    },

    {
        id: 15,
        title: 'Darling in the franxx',
        image: 'https://firebasestorage.googleapis.com/v0/b/anime-sanctuary-bb873.appspot.com/o/images%2Fdarling_in_the_franxx.jpg?alt=media&token=41faccf4-cafc-4b5b-848c-7a60b0125a67',
        genre: ['Action', 'Sci-Fi', 'Romance'],
        episodes: 24,
        seasons: 1,
        type: 'TV',
        cruncyroll: 'https://www.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx',
        youtube: 'https://youtu.be/xiNeXCUosSg?si=FCCbRrNC3x7RbZox',
        description: "",
        url: 'https://myanimelist.net/anime/35849/Darling_in_the_FranXX?q=darling%20&cat=anime',
    },
]

export default Underrated

